export * from './ProteinFallback';
export * from './BeautyFallback';
export * from './BabyCareFallback';
export * from './PetCareFallback';
export * from './ElectronicsFallback';
export * from './HomeKitchenFallback';
export * from './FreshFallback';
export * from './ChocolateFallback';
export * from './GeneralProductFallback';
